Running the tests from terminal failing since the spring boot upgrade, caused by the junit-platform-surefire-provider plugin, so removing it.
org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process