Updating the cucumber-reporting.version has resulted in a NoClassDefFoundError.
So, excluded plexus to avoid the following exception:
java.lang.NoClassDefFoundError: org/codehaus/plexus/util/xml/pull/XmlPullParserException
The newer version which comes through cucumber reporting does not have the xml package and
hence the error; but the one which comes through the fluentlenium-junit-jupiter dependency,
is an older version and still has xml package.