(WIP) - Resolved the following error by removing `net.bytebuddy:byte-buddy`:
Caused by: java.lang.NoClassDefFoundError: net/bytebuddy/NamingStrategy$SuffixingRandom$BaseNameResolver

`net.bytebuddy:byte-buddy` maven dependency was added for the test scope in the [pom.xml](../pom.xml) file as part of
the Java 20 upgrade, but that's causing problem after Springboot's upgrade, so solution is just to remove it from the
[pom.xml](../pom.xml) as it'll be loaded by few other dependencies.