Fix for the following error is WIP as the whole SecurityConfig needs to be rewritten with spring boot 3:
BeanCreationException: Failed to instantiate [jakarta.servlet.Filter]